### PR TITLE
Removing RecurringDonations_AddDonationsBTN.page

### PR DESCRIPTION
**Pull request by njjc**
# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Comment by davidhabib** [comment]
@njjc we kept all the old Visualforce pages in the old packages and fixed them up to refer to our new pages, so if anyone had buttons to those old pages they wouldn't be broken. so I'm not sure deleting it is the right solution

**Comment by judisohn** [comment]
As @njjc mentioned in chat: the page doesn't go away on deletion, it just enables deletion in the org

**Comment by force2b** [comment]
@judisohn I wonder if we should finish off this work that Nic started way back when.

**Comment by judisohn** [comment]
@force2b No objection from me. :-)

**Comment by force2b** [comment]
@judisohn Actually it appears that the page files were previously removed in v3.11 re #59. Closing this since there's nothing on it.

**Pull request closed without merging**
